# Find ODBCPP
# Merder Kim <hoxnox@gmail.com>
#
# input:
#  LIBODBCPP_ROOT
#
# output:
#  ODBCPP_FOUND
#  ODBCPP_INCLUDE_DIR
#  ODBCPP_LIBRARIES
#

if(ODBCPP_INCLUDE_DIR AND ODBCPP_LIBRARIES)
	set(ODBCPP_FIND_QUITELY TRUE) # cached
endif(ODBCPP_INCLUDE_DIR AND ODBCPP_LIBRARIES)

if(NOT DEFINED ODBCPP_ROOT)
	set(ODBCPP_ROOT /usr /usr/local $ENV{ODBCPP_ROOT})
endif(NOT DEFINED ODBCPP_ROOT)

find_path(ODBCPP_INCLUDE_DIR odbc++
	PATHS ${ODBCPP_ROOT}
	PATH_SUFFIXES odbc++/include odbcpp/include include
)

find_library(ODBCPP_LIBRARIES
	NAMES odbc++
	PATHS ${LIB_PATHS}
	PATH_SUFFIXES lib
)
mark_as_advanced(ODBCPP_INCLUDE_DIR ODBCPP_LIBRARIES)

include("${CMAKE_ROOT}/Modules/FindPackageHandleStandardArgs.cmake")
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ODBCPP DEFAULT_MSG ODBCPP_INCLUDE_DIR ODBCPP_LIBRARIES)

